### ISSUE TITLE
Unable to run yarn in TFS2015

### ISSUE THREAD

**Issue by newbish** [geeklearningio/gl-vsts-tasks-yarn#46]
# Are you reporting a bug or a feature request ?
* [x] Bug
* [ ] Feature request

# Description
Unable to run run yarn task after install task.
2018-02-27T21:53:31.1404186Z Set workingFolder to default: D:\TFSBuild\tasks\Yarn\2.4.999
2018-02-27T21:53:31.8884718Z ##[debug]agent.workFolder=D:\TFSBuild\_work
2018-02-27T21:53:31.8944677Z ##[debug]loading inputs and endpoints
...
2018-02-27T21:53:31.8994698Z ##[debug]loaded 12
2018-02-27T21:53:32.6915198Z ##[debug]check path : D:\TFSBuild\tasks\Yarn\2.4.999\task.json
2018-02-27T21:53:32.6915198Z ##[debug]set resource file to: D:\TFSBuild\tasks\Yarn\2.4.999\task.json
2018-02-27T21:53:32.6915198Z ##[debug]system.culture=en-US
2018-02-27T21:53:33.0005407Z ##[debug]which 'yarn'
2018-02-27T21:53:33.0285447Z ##[debug]not found
2018-02-27T21:53:33.0295439Z ##[debug]Arguments=null
2018-02-27T21:53:33.0335440Z ##[debug]ProjectDirectory=D:\TFSBuild\_work\76\s\Web
2018-02-27T21:53:33.0335440Z ##[debug]customRegistry=useNpmrc
2018-02-27T21:53:33.0345439Z ##[debug]customFeed=null
2018-02-27T21:53:33.0345439Z ##[debug]customEndpoint=null
2018-02-27T21:53:33.0355436Z ##[debug]Error: couldn't locate Yarn
2018-02-27T21:53:33.0355436Z ##[debug]Error: couldn't locate Yarn
2018-02-27T21:53:33.0365447Z     at D:\TFSBuild\tasks\Yarn\2.4.999\yarnTask.js:58:23
2018-02-27T21:53:33.0365447Z     at next (native)
2018-02-27T21:53:33.0375457Z     at D:\TFSBuild\tasks\Yarn\2.4.999\yarnTask.js:7:71
2018-02-27T21:53:33.0375457Z     at __awaiter (D:\TFSBuild\tasks\Yarn\2.4.999\yarnTask.js:3:12)
2018-02-27T21:53:33.0375457Z     at yarnExec (D:\TFSBuild\tasks\Yarn\2.4.999\yarnTask.js:55:12)
2018-02-27T21:53:33.0385439Z     at Object.<anonymous> (D:\TFSBuild\tasks\Yarn\2.4.999\yarnTask.js:132:1)
2018-02-27T21:53:33.0385439Z     at Module._compile (module.js:413:34)
2018-02-27T21:53:33.0385439Z     at Object.Module._extensions..js (module.js:422:10)
2018-02-27T21:53:33.0395437Z     at Module.load (module.js:357:32)
2018-02-27T21:53:33.0395437Z     at Function.Module._load (module.js:314:12)
2018-02-27T21:53:33.0405438Z ##[debug]task result: Failed
2018-02-27T21:53:33.0475471Z ##[error]Error: couldn't locate Yarn
2018-02-27T21:53:33.0595559Z ##[debug]Agent.BuildDirectory=D:\TFSBuild\_work\76
2018-02-27T21:53:33.0605519Z ##[debug]testing directory 'D:\TFSBuild\_work\76\npm'
2018-02-27T21:53:33.0605519Z ##[debug]testing directory 'D:\TFSBuild\_work\76'
2018-02-27T21:53:33.0605519Z ##[debug]mkdir 'D:\TFSBuild\_work\76\npm'
2018-02-27T21:53:33.0615559Z ##[debug]rm -rf D:\TFSBuild\_work\76\npm
2018-02-27T21:53:33.0615559Z ##[debug]removing directory

# System information

**VSTS or TFS:**
* [ ] VSTS
* [x] TFS

**Agent:**
* [ ] Hosted
* [x] Custom

**OS:**
* [x] Windows
* [ ] Mac
* [ ] Linux

**Yarn version:**
*1.5.1**

**Node version:**
*8.9.1**

**Comment by sandorfr** [comment]
We do not support TFS2015 as it is using the legacy built agent which
completely stale and does not have tool installer and other recent features.

That said, You might be able to install yarn yourself (make sure it’s in
the path) and add the capability to your agent.
